devtools::load_all()
library(reshape2)

load("./data-analysis/auc.RData")
auc_df <- Reduce(rbind, split_auc)
auc_df$year <- paste0("y", auc_df$year)
auc_wide <- dcast(auc_df, feid ~ year)
write.csv(auc_wide, file="./output/auc.csv", row.names=FALSE)

load("./data-analysis/quant.RData")
quant_df <- Reduce(rbind, split_quant)
quant_df$year <- paste0("y", quant_df$year)
quant_wide <- dcast(quant_df, feid ~ year)
write.csv(quant_wide, file="./output/quant.csv", row.names=FALSE)

load("./data-analysis/streak.RData")
streak_df_0.1 <- Reduce(rbind, split_streak_0.1)
streak_df_0.1$year <- paste0("y", streak_df_0.1$year)
streak_wide_0.1 <- dcast(streak_df_0.1, feid ~ year)
write.csv(streak_wide_0.1, file="./output/streak_01.csv", row.names=FALSE)
streak_df_0.2 <- Reduce(rbind, split_streak_0.2)
streak_df_0.2$year <- paste0("y", streak_df_0.2$year)
streak_wide_0.2 <- dcast(streak_df_0.2, feid ~ year)
write.csv(streak_wide_0.2, file="./output/streak_02.csv", row.names=FALSE)
streak_df_0.3 <- Reduce(rbind, split_streak_0.3)
streak_df_0.3$year <- paste0("y", streak_df_0.3$year)
streak_wide_0.3 <- dcast(streak_df_0.3, feid ~ year)
write.csv(streak_wide_0.3, file="./output/streak_03.csv", row.names=FALSE)
